version: '3.8'

services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo_db
      - SPRING_DATASOURCE_USERNAME=todouser
      - SPRING_DATASOURCE_PASSWORD=todopassword
    depends_on:
      - db_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready


volumes:
  postgres-data: